version: 2.2.0-ci-{branch}-{build}
image: Visual Studio 2013
configuration: Release
platform: ARM64
shallow_clone: true
before_build:
- ps: (Get-Content "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\ntsecapi.h") | %{$_ -replace "^RtlDecryptMemory\($", "__stdcall RtlDecryptMemory("} | Set-Content "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\ntsecapi.h"
build:
  parallel: true
  verbosity: normal
artifacts:
- path: mimikatz_trunk_*
